### ISSUE TITLE
Review and possibly simplify the code

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-3d-mannequin#6]
Josh worked on this character directly, I just briefly looked at the code, so it could use a second pair of eyes. Go through the character's code and look for places where it can be simplified or refined.

Josh suggested to replace rotation logic with quaternions, which would shorten the code and prevent issues like gimbal lock or the need to unwind in some case. He went with rotation in degrees as this will end up in a tutorial, because quaternions are harder to understand compared to angles.

But as quaternions solve some problems that can be tricky when you use angles and can easily produce smooth, graceful rotations, we should consider using them.

## Tasks

- [ ] Review the code and simplify if possible
- [ ] Document the main scripts with a docstring at the top
- [ ] Figure out if we should use quaternions (you can create a new task for that)
