### ISSUE TITLE
Prepare for release on the asset library

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-3d-mannequin#7]
To do after/along with #6 

This open mannequin is a free project for the community. The goal is to have it on the [Godot asset library](https://godotengine.org/asset-library/) so people can download it and get started prototyping their games.

## Tasks

- [x] Write a getting started guide
- [x] Adapt the code and project so it's easy to reuse in a new Godot game
- [x] Create the first GitHub release, with a copy of the .blend file attached, so people can use and contribute animations
